<?php
declare(strict_types=1);

require_once __DIR__ . '/../api/config/bootstrap.php';
require_once __DIR__ . '/../api/core/Database.php';

$db = \App\Core\Database::getConnection();

echo "Seeding full creative October 2026 content...\n";

// 1. Clear any existing activities in October 2026 to avoid duplicates
$stmt = $db->prepare("DELETE FROM activities WHERE date >= '2026-10-01' AND date <= '2026-10-31'");
$stmt->execute();
echo "Cleared existing October activities.\n";

// 2. Prepare October 2026 Activities
$octoberActivities = [
    // Oct 1 (Thursday)
    [
        'user_id' => 1,
        'type' => 'CLASS',
        'title' => 'কোরআন হিফজ ও তাজবিদ পর্যালোচনা',
        'description' => 'উন্নত শিক্ষার্থীদের সূরা আন-নিসা মাখরাজ ও সিফাত সহ মুখস্থ নিরীক্ষণ।',
        'date' => '2026-10-01',
        'start_time' => '09:00:00',
        'end_time' => '10:15:00',
        'location' => 'অনলাইন স্টুডিও ও জুম',
        'topic' => 'মাখরাজ ও ওয়াকফের সঠিক নিয়ম',
        'status' => 'COMPLETED',
        'priority' => 'HIGH',
        'preparation_required' => 0,
        'travel_required' => 0,
    ],
    [
        'user_id' => 1,
        'type' => 'MEETING',
        'title' => 'মাসিক দ্বীনি পাঠ্যক্রম ও প্রকাশনা বৈঠক',
        'description' => 'অনলাইন মাদরাসার ত্রৈমাসিক সিলেবাস ও নতুন পাঠ্যপুস্তক সম্পাদনা পরিষদ।',
        'date' => '2026-10-01',
        'start_time' => '15:30:00',
        'end_time' => '17:00:00',
        'location' => 'আল-কুরআন একাডেমি কনফারেন্স রুম, ধানমন্ডি',
        'topic' => 'নতুন সেমিস্টারের কারিকুলাম অনুমোদন',
        'status' => 'COMPLETED',
        'priority' => 'MEDIUM',
        'preparation_required' => 1,
        'travel_required' => 1,
    ],
    [
        'user_id' => 1,
        'type' => 'CLASS',
        'title' => 'তাফসিরুল কুরআন ধারাবাহিক দরস: সূরা আল-বাকারাহ #১৩',
        'description' => 'সূরা আল-বাকারাহ আয়াত ১২০-১২৯ এর ব্যাকরণিক বিশ্লেষণ ও তাফসির।',
        'date' => '2026-10-01',
        'start_time' => '21:00:00',
        'end_time' => '22:15:00',
        'location' => 'অনলাইন লাইভ স্টুডিও',
        'topic' => 'ইবরাহিম (আ.)-এর দোয়া ও কাবাগৃহ নির্মাণ',
        'status' => 'COMPLETED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 0,
    ],

    // Oct 2 (Friday - 1st Jumuah)
    [
        'user_id' => 1,
        'type' => 'JUMUAH',
        'title' => "জুমু'আ খুতবাহ: কুরআনের আলোকে সামাজিক সদাচার ও প্রতিবেশীর অধিকার",
        'description' => "সোবহানবাগ জামে মসজিদে জুমু'আর প্রস্তুতি, বয়ান ও জুমার সালাতের ইমামতি।",
        'date' => '2026-10-02',
        'start_time' => '12:15:00',
        'end_time' => '14:00:00',
        'location' => 'সোবহানবাগ জামে মসজিদ, ধানমন্ডি ২৭, ঢাকা',
        'topic' => 'সামাজিক ভ্রাতৃত্ব ও প্রতিবেশীর হক',
        'status' => 'COMPLETED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 1,
    ],
    [
        'user_id' => 1,
        'type' => 'PROGRAMME',
        'title' => 'সাপ্তাহিক পারিবারিক পরামর্শ ও উন্মুক্ত প্রশ্নোত্তর',
        'description' => 'মসজিদ কমিটির শুভাকাঙ্ক্ষী ও মুসল্লিদের সাথে সংক্ষিপ্ত উন্মুক্ত মজলিস।',
        'date' => '2026-10-02',
        'start_time' => '17:30:00',
        'end_time' => '19:00:00',
        'location' => 'সোবহানবাগ মসজিদ লাইব্রেরি কক্ষ',
        'topic' => 'পারিবারিক অশান্তি নিরসনে ইসলামের ভূমিকা',
        'status' => 'COMPLETED',
        'priority' => 'MEDIUM',
        'preparation_required' => 0,
        'travel_required' => 0,
    ],

    // Oct 3 (Saturday - Today)
    [
        'user_id' => 1,
        'type' => 'CLASS',
        'title' => 'কোরআন হিফজ ও তাজবিদ পাঠদান',
        'description' => 'নিয়মিত হিফজ শিক্ষার্থীদের নতুন পাঠ শ্রবণ ও ইয়াদ নিরীক্ষণ।',
        'date' => '2026-10-03',
        'start_time' => '09:00:00',
        'end_time' => '10:00:00',
        'location' => 'অনলাইন স্টুডিও',
        'topic' => 'সূরা আন-নিসা পারা ৫ তিলাওয়াত',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 0,
        'travel_required' => 0,
    ],
    [
        'user_id' => 1,
        'type' => 'MEETING',
        'title' => 'জাতীয় সীরাত সেমিনার আয়োজন প্রস্তুতি সভা',
        'description' => 'আসন্ন সীরাত সেমিনারের অতিথি তালিকা ও প্রবন্ধ বাছাই কমিটি।',
        'date' => '2026-10-03',
        'start_time' => '15:00:00',
        'end_time' => '16:30:00',
        'location' => 'ইসলামিক রিসার্চ একাডেমি, ধানমন্ডি',
        'topic' => 'সেমিনার সেশন ও বক্তা সমন্বয়',
        'status' => 'CONFIRMED',
        'priority' => 'MEDIUM',
        'preparation_required' => 1,
        'travel_required' => 1,
    ],
    [
        'user_id' => 1,
        'type' => 'CLASS',
        'title' => 'তাফসিরুল কুরআন ধারাবাহিক দরস: সূরা আল-বাকারাহ #১৪',
        'description' => 'সূরা আল-বাকারাহ আয়াত ১৩০-১৪১ কিবলা পরিবর্তনের প্রেক্ষাপট ও আত্মিক তাৎপর্য।',
        'date' => '2026-10-03',
        'start_time' => '21:00:00',
        'end_time' => '22:15:00',
        'location' => 'অনলাইন স্টুডিও ও জুম লাইভ',
        'topic' => 'তাহবীলুল কিবলা ও মধ্যমপন্থী উম্মাহ',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 0,
    ],

    // Oct 4 (Sunday)
    [
        'user_id' => 1,
        'type' => 'CLASS',
        'title' => 'বালাগাত ও আরবি অলংকার শাস্ত্রের মূলনীতি',
        'description' => 'ইলমুল মাআনী ও বয়ান শাস্ত্রের প্রয়োগিক বিশ্লেষণ।',
        'date' => '2026-10-04',
        'start_time' => '10:30:00',
        'end_time' => '12:00:00',
        'location' => 'উচ্চতর আরবি একাডেমি, ঢাকা',
        'topic' => 'কুরআনিক ইজাজ ও ফাসাহাত',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 1,
    ],
    [
        'user_id' => 1,
        'type' => 'PROGRAMME',
        'title' => 'জাতীয় তাফসীরুল কুরআন ও সীরাত কনফারেন্স ২০২৬',
        'description' => 'রাজধানীর কেন্দ্রীয় মিলনায়তনে প্রধান আলোচক হিসেবে বিশেষ ভাষণ।',
        'date' => '2026-10-04',
        'start_time' => '17:00:00',
        'end_time' => '19:30:00',
        'location' => 'সেন্ট্রাল সেমিনার অডিটোরিয়াম, কাকরাইল, ঢাকা',
        'topic' => 'সমকালীন পৃথিবীতে নববী জীবনাদর্শের প্রাসঙ্গিকতা',
        'status' => 'CONFIRMED',
        'priority' => 'URGENT',
        'preparation_required' => 1,
        'travel_required' => 1,
    ],

    // Oct 5 (Monday)
    [
        'user_id' => 1,
        'type' => 'CLASS',
        'title' => 'কোরআন হিফজ ও তাজবিদ',
        'description' => 'অনলাইন নিয়মিত ক্লাস · ব্যাচ ০১।',
        'date' => '2026-10-05',
        'start_time' => '09:00:00',
        'end_time' => '10:00:00',
        'location' => 'অনলাইন স্টুডিও',
        'topic' => 'হৃদয়ে কুরআন ধারণের বৈজ্ঞানিক পদ্ধতি',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 0,
        'travel_required' => 0,
    ],
    [
        'user_id' => 1,
        'type' => 'CLASS',
        'title' => 'তাফসিরুল কুরআন ধারাবাহিক দরস: সূরা আল-বাকারাহ #১৫',
        'description' => 'কিবলা পরিবর্তন পরবর্তী মুসলিম উম্মাহর দায়িত্ব ও ইবাদতের নিষ্ঠা।',
        'date' => '2026-10-05',
        'start_time' => '21:00:00',
        'end_time' => '22:00:00',
        'location' => 'অনলাইন স্টুডিও',
        'topic' => 'সবর ও সালাতের মাধ্যমে আল্লাহর সাহায্য প্রার্থনা',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 0,
    ],

    // Oct 6 (Tuesday)
    [
        'user_id' => 1,
        'type' => 'MEETING',
        'title' => 'উচ্চতর গবেষণা পরিষদ কারিকুলাম চূড়ান্তকরণ সভা',
        'description' => 'ইসলামিক রিসার্চ কাউন্সিলের ফেলোশিপ কারিকুলাম ও গবেষক নিয়োগ।',
        'date' => '2026-10-06',
        'start_time' => '11:00:00',
        'end_time' => '13:00:00',
        'location' => 'গবেষণা ভবন, ধানমন্ডি',
        'topic' => 'আধুনিক যুগের ফিকহি গবেষণা নীতিমালা',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 1,
    ],
    [
        'user_id' => 1,
        'type' => 'CLASS',
        'title' => 'উচ্চতর হাদিস পাঠদান: মিশকাতুল মাসাবীহ',
        'description' => 'কিতাবুল ইলম ও কিতাবুত তাহারাত এর প্রামাণ্য বিশ্লেষণ।',
        'date' => '2026-10-06',
        'start_time' => '18:30:00',
        'end_time' => '20:00:00',
        'location' => 'হলকা স্টুডিও, লালমাটিয়া',
        'topic' => 'সনদ ও মতনের সূক্ষ্ম পার্থক্য বিশ্লেষণ',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 1,
    ],

    // Oct 7 (Wednesday)
    [
        'user_id' => 1,
        'type' => 'CLASS',
        'title' => 'কোরআন হিফজ ও তাজবিদ',
        'description' => 'অনলাইন নিয়মিত ক্লাস · ব্যাচ ০২।',
        'date' => '2026-10-07',
        'start_time' => '09:00:00',
        'end_time' => '10:00:00',
        'location' => 'অনলাইন স্টুডিও',
        'topic' => 'ইখফা ও গুন্নাহর প্রায়োগিক উচ্চারণ',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 0,
        'travel_required' => 0,
    ],
    [
        'user_id' => 1,
        'type' => 'PROGRAMME',
        'title' => 'প্যান ভিশন টিভি লাইভ: সমকালীন জিজ্ঞাসার কুরআনভিত্তিক জবাব',
        'description' => 'সরাসরি টেলিভিশন সম্প্রচার ও বৈশ্বিক দর্শকদের টেলিফোনিক প্রশ্নের উত্তর।',
        'date' => '2026-10-07',
        'start_time' => '19:00:00',
        'end_time' => '20:15:00',
        'location' => 'প্যান ভিশন টিভি স্টুডিও, বাংলামোটর, ঢাকা',
        'topic' => 'আধুনিক অর্থব্যবস্থায় সুদমুক্ত জীবন',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 1,
    ],
    [
        'user_id' => 1,
        'type' => 'CLASS',
        'title' => 'তাফসিরুল কুরআন ধারাবাহিক দরস: সূরা আল-বাকারাহ #১৬',
        'description' => 'সূরা আল-বাকারাহ আয়াত ১৫৩-১৬৫ আল্লাহর নিদর্শন ও ভালোবাসার সঠিক মানদণ্ড।',
        'date' => '2026-10-07',
        'start_time' => '21:00:00',
        'end_time' => '22:00:00',
        'location' => 'অনলাইন স্টুডিও',
        'topic' => 'পরীক্ষার মাঝে ধৈর্য ও শহীদের মর্যাদা',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 0,
    ],

    // Oct 8 (Thursday)
    [
        'user_id' => 1,
        'type' => 'CLASS',
        'title' => 'বালাগাত ও ফাসাহাহ শাস্ত্রের উন্নত ক্লাস',
        'description' => 'ইলমুল বাদি ও অলংকারের সৌন্দর্য ও কুরআনিক ব্যবহার।',
        'date' => '2026-10-08',
        'start_time' => '10:00:00',
        'end_time' => '11:30:00',
        'location' => 'অনলাইন স্টুডিও',
        'topic' => 'তাজনিস ও তিবাঁকের সৌন্দর্য',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 0,
    ],
    [
        'user_id' => 1,
        'type' => 'MEETING',
        'title' => "আগামীকালের জুমু'আ খুতবাহর নোট ও রেফারেন্স চূড়ান্তকরণ",
        'description' => 'বাইতুল আমান জামে মসজিদে বয়ানের হাদিস ও তাফসির রেফারেন্স সাজানো।',
        'date' => '2026-10-08',
        'start_time' => '21:30:00',
        'end_time' => '22:30:00',
        'location' => 'ব্যক্তিগত লাইব্রেরি কক্ষ',
        'topic' => 'পারিবারিক সুখ ও পিতা-মাতার অধিকার',
        'status' => 'CONFIRMED',
        'priority' => 'MEDIUM',
        'preparation_required' => 0,
        'travel_required' => 0,
    ],

    // Oct 9 (Friday - 2nd Jumuah)
    [
        'user_id' => 1,
        'type' => 'JUMUAH',
        'title' => "জুমু'আ খুতবাহ: পারিবারিক শান্তি, দাম্পত্য বোঝাপড়া ও পিতা-মাতার হক",
        'description' => 'বাইতুল আমান জামে মসজিদে জুমার পূর্ব বয়ান ও সালাত পরিচালনা।',
        'date' => '2026-10-09',
        'start_time' => '12:00:00',
        'end_time' => '14:00:00',
        'location' => 'বাইতুল আমান জামে মসজিদ, ধানমন্ডি, ঢাকা',
        'topic' => 'পারিবারিক সম্প্রীতি ও নেক সন্তানের দোয়া',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 1,
    ],
    [
        'user_id' => 1,
        'type' => 'PROGRAMME',
        'title' => 'তরুণ সমাজের মুখোমুখি: ক্যারিয়ার ও নৈতিকতার দ্বৈরথ',
        'description' => 'বিশ্ববিদ্যালয় ও কলেজ পড়ুয়া শিক্ষার্থীদের সাথে উন্মুক্ত সেমিনার।',
        'date' => '2026-10-09',
        'start_time' => '17:30:00',
        'end_time' => '19:30:00',
        'location' => 'ইঞ্জিনিয়ার্স ইনস্টিটিউশন সেমিনার হল, রমনা',
        'topic' => 'আধুনিক পেশাগত জীবনে ইসলামি মূল্যবোধ',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 1,
    ],

    // Oct 10 (Saturday)
    [
        'user_id' => 1,
        'type' => 'CLASS',
        'title' => 'কোরআন হিফজ ও তাজবিদ পাঠদান',
        'description' => 'সাপ্তাহিক মূল্যায়ন ও হিফজ প্রতিযোগিতা।',
        'date' => '2026-10-10',
        'start_time' => '09:00:00',
        'end_time' => '10:30:00',
        'location' => 'অনলাইন স্টুডিও',
        'topic' => 'পারা ৫-৭ মুখস্থ যাচাই',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 0,
        'travel_required' => 0,
    ],
    [
        'user_id' => 1,
        'type' => 'CLASS',
        'title' => 'তাফসিরুল কুরআন ধারাবাহিক দরস: সূরা আল-বাকারাহ #১৭',
        'description' => 'হালাল রিজিক ও শয়তানের পদাঙ্ক পরিহার সংক্রান্ত আয়াতসমূহের তাফসির।',
        'date' => '2026-10-10',
        'start_time' => '21:00:00',
        'end_time' => '22:15:00',
        'location' => 'অনলাইন স্টুডিও',
        'topic' => 'হালাল আহার ও অন্তরের সুস্থতা',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 0,
    ],

    // Oct 11 (Sunday)
    [
        'user_id' => 1,
        'type' => 'PROGRAMME',
        'title' => 'জাতীয় প্রেস ক্লাব গোলটেবিল বৈঠক: যাকাত ব্যবস্থাপনা ও দারিদ্র্য বিমোচন',
        'description' => 'জাতীয় অর্থনীতিবিদ, ইসলামিক স্কলার ও গবেষকদের যৌথ গোলটেবিল সম্মেলন।',
        'date' => '2026-10-11',
        'start_time' => '10:30:00',
        'end_time' => '13:00:00',
        'location' => 'জাতীয় প্রেস ক্লাব ভিআইপি লাউঞ্জ, তোপখানা রোড, ঢাকা',
        'topic' => 'প্রাতিষ্ঠানিক যাকাত সংগ্রহ ও বিতরণ মডেল',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 1,
    ],

    // Oct 12 (Monday)
    [
        'user_id' => 1,
        'type' => 'CLASS',
        'title' => 'কোরআন হিফজ ও তাজবিদ',
        'description' => 'অনলাইন ক্লাস · ব্যাচ ০১।',
        'date' => '2026-10-12',
        'start_time' => '09:00:00',
        'end_time' => '10:00:00',
        'location' => 'অনলাইন স্টুডিও',
        'topic' => 'তিলাওয়াতে সৌন্দর্য বৃদ্ধির কৌশল',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 0,
        'travel_required' => 0,
    ],
    [
        'user_id' => 1,
        'type' => 'CLASS',
        'title' => 'তাফসিরুল কুরআন ধারাবাহিক দরস: সূরা আল-বাকারাহ #১৮',
        'description' => 'কিসাস, অসিয়ত ও রমাদানের সিয়াম সংক্রান্ত বিধিবিধান।',
        'date' => '2026-10-12',
        'start_time' => '21:00:00',
        'end_time' => '22:15:00',
        'location' => 'অনলাইন স্টুডিও',
        'topic' => 'সিয়ামের আধ্যাত্মিক ও সামাজিক দর্শন',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 0,
    ],

    // Oct 14 (Wednesday)
    [
        'user_id' => 1,
        'type' => 'MEETING',
        'title' => 'ইসলামিক বিশ্ববিদ্যালয়ের সিলেবাস রিভিউ কমিটি বৈঠক',
        'description' => 'কুরআনিক স্টাডিজ ও দাওয়াহ বিভাগের সমন্বিত পাঠ্যসূচি সংস্কার।',
        'date' => '2026-10-14',
        'start_time' => '11:00:00',
        'end_time' => '13:30:00',
        'location' => 'ঢাকা বিশ্ববিদ্যালয় সংলগ্ন রিসার্চ ইনস্টিটিউট',
        'topic' => 'বিশ্ববিদ্যালয় পর্যায়ের ইসলামিক পাঠ্যক্রম',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 1,
    ],
    [
        'user_id' => 1,
        'type' => 'CLASS',
        'title' => 'তাফসিরুল কুরআন ধারাবাহিক দরস: সূরা আল-বাকারাহ #১৯',
        'description' => 'হজ্জ ও উমরার বিধিবিধান এবং জীবনের চূড়ান্ত সফর।',
        'date' => '2026-10-14',
        'start_time' => '21:00:00',
        'end_time' => '22:15:00',
        'location' => 'অনলাইন স্টুডিও',
        'topic' => 'হজ্জের ইতিহাস ও আত্মিক বিপ্লব',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 0,
    ],

    // Oct 15 (Thursday)
    [
        'user_id' => 1,
        'type' => 'TRAVEL',
        'title' => 'চট্টগ্রাম সফর: ঐতিহাসিক বাৎসরিক সীরাতুন্নবী (সা.) মহাসমাবেশ',
        'description' => 'চট্টগ্রাম জমিয়াতুল ফালাহ চত্বরে বাৎসরিক সম্মেলনে প্রধান অতিথি হিসেবে আগমন।',
        'date' => '2026-10-15',
        'start_time' => '14:00:00',
        'end_time' => '21:30:00',
        'location' => 'জমিয়াতুল ফালাহ জাতীয় মসজিদ ময়দান, ওয়াসা মোড়, চট্টগ্রাম',
        'topic' => 'উম্মাহর ঐক্য ও রাসূলুল্লাহ (সা.)-এর সুন্নাহর পুনর্জাগরণ',
        'status' => 'CONFIRMED',
        'priority' => 'URGENT',
        'preparation_required' => 1,
        'travel_required' => 1,
    ],

    // Oct 16 (Friday - 3rd Jumuah)
    [
        'user_id' => 1,
        'type' => 'JUMUAH',
        'title' => "জুমু'আ খুতবাহ: ডিজিটাল যুগে সন্তানের লালন-পালন ও তরুণ সমাজের আত্মশুদ্ধি",
        'description' => 'গুলশান সোসাইটি জামে মসজিদে জুমুআর বয়ান ও নামাযের ইমামতি।',
        'date' => '2026-10-16',
        'start_time' => '12:00:00',
        'end_time' => '14:00:00',
        'location' => 'গুলশান সোসাইটি জামে মসজিদ, রোড ৬৩, গুলশান ২, ঢাকা',
        'topic' => 'সোশ্যাল মিডিয়া, আসক্তি ও অন্তরের হেফাজত',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 1,
    ],

    // Oct 17 (Saturday)
    [
        'user_id' => 1,
        'type' => 'CLASS',
        'title' => 'তাফসিরুল কুরআন ধারাবাহিক দরস: সূরা আল-বাকারাহ #২০',
        'description' => 'ইনফাক ফি সাবিলিল্লাহ ও আল্লাহর রাস্তায় খরচের গুরুত্ব।',
        'date' => '2026-10-17',
        'start_time' => '21:00:00',
        'end_time' => '22:15:00',
        'location' => 'অনলাইন স্টুডিও',
        'topic' => 'দান-সদকার বরকত ও রিয়া মুক্ত নিয়ত',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 0,
    ],

    // Oct 19 (Monday)
    [
        'user_id' => 1,
        'type' => 'PROGRAMME',
        'title' => 'কুরআন অনুবাদ ও তাফসির সাহিত্য শীর্ষক আন্তর্জাতিক সিম্পোজিয়াম',
        'description' => 'বাংলা একাডেমি আব্দুল করিম সাহিত্যবিশারদ মিলনায়তনে গবেষক অধিবেশন।',
        'date' => '2026-10-19',
        'start_time' => '15:00:00',
        'end_time' => '18:00:00',
        'location' => 'বাংলা একাডেমি মিলনায়তন, ঢাকা',
        'topic' => 'বাংলা ভাষায় তাফসির চর্চার ঐতিহ্য ও বর্তমান রূপরেখা',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 1,
    ],

    // Oct 21 (Wednesday)
    [
        'user_id' => 1,
        'type' => 'CLASS',
        'title' => 'তাফসিরুল কুরআন ধারাবাহিক দরস: সূরা আল-বাকারাহ #২১',
        'description' => 'আয়াতুল কুরসি ও তার অতুলনীয় তাওহিদী তাৎপর্য।',
        'date' => '2026-10-21',
        'start_time' => '21:00:00',
        'end_time' => '22:30:00',
        'location' => 'অনলাইন স্টুডিও',
        'topic' => 'আয়াতুল কুরসির তাফসির ও আল্লাহর সার্বভৌমত্ব',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 0,
    ],

    // Oct 23 (Friday - 4th Jumuah)
    [
        'user_id' => 1,
        'type' => 'JUMUAH',
        'title' => "জুমু'আ খুতবাহ: অর্থনৈতিক সুবিচার, ব্যবসায়িক সততা ও হালাল জীবিকার বরকত",
        'description' => 'উত্তরা সেক্টর ৭ জামে মসজিদে খুতবাহ ও জুমার জামাত।',
        'date' => '2026-10-23',
        'start_time' => '12:15:00',
        'end_time' => '14:00:00',
        'location' => 'উত্তরা সেক্টর ৭ জামে মসজিদ, রোড ১, উত্তরা, ঢাকা',
        'topic' => 'লেনদেনে সততা ও ওজন-পরিমাপে নিষ্ঠা',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 1,
    ],

    // Oct 25 (Sunday)
    [
        'user_id' => 1,
        'type' => 'PROGRAMME',
        'title' => 'সিলেট বিভাগীয় উলামা ও ইমাম সম্মেলন ২০২৬',
        'description' => 'সিলেটের দরগাহ মসজিদ মিলনায়তনে ইমাম ও আলেমদের জাতীয় প্রশিক্ষণ কর্মশালা।',
        'date' => '2026-10-25',
        'start_time' => '10:00:00',
        'end_time' => '14:30:00',
        'location' => 'শাহজালাল দরগাহ মসজিদ মিলনায়তন, সিলেট',
        'topic' => 'আধুনিক সমাজে খতীবদের নেতৃত্বের দক্ষতা ও সমাজ সংস্কার',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 1,
    ],

    // Oct 28 (Wednesday)
    [
        'user_id' => 1,
        'type' => 'PROGRAMME',
        'title' => 'ইয়ুথ ইসলামিক লিডারশিপ ও নৈতিক জাগরণ কনভেনশন',
        'description' => 'আন্তর্জাতিক কনভেনশন সিটি বসুন্ধরায় সারা দেশের পাঁচ হাজার তরুণের সমাবেশ।',
        'date' => '2026-10-28',
        'start_time' => '16:00:00',
        'end_time' => '20:00:00',
        'location' => 'আইসিসিবি (ICCB) হল ৪, বসুন্ধরা আবাসিক এলাকা, ঢাকা',
        'topic' => 'আগামীর বাংলাদেশ গড়ায় তাকওয়াভিত্তিক নেতৃত্বের রূপরেখা',
        'status' => 'CONFIRMED',
        'priority' => 'URGENT',
        'preparation_required' => 1,
        'travel_required' => 1,
    ],

    // Oct 30 (Friday - 5th Jumuah)
    [
        'user_id' => 1,
        'type' => 'JUMUAH',
        'title' => "জুমু'আ খুতবাহ: আখেরাতমুখী জীবনদর্শন, সত্যবাদিতা ও তাকওয়ার প্রভাব",
        'description' => 'বায়তুল মোকাররম জাতীয় মসজিদে অতিথি খতীব হিসেবে খুতবাহ পেশ ও ইমামতি।',
        'date' => '2026-10-30',
        'start_time' => '11:45:00',
        'end_time' => '14:00:00',
        'location' => 'বায়তুল মোকাররম জাতীয় মসজিদ, পল্টন, ঢাকা',
        'topic' => 'মৃত্যু, বারযাখ ও জান্নাতকামী মানুষের জীবন',
        'status' => 'CONFIRMED',
        'priority' => 'URGENT',
        'preparation_required' => 1,
        'travel_required' => 1,
    ],

    // Oct 31 (Saturday)
    [
        'user_id' => 1,
        'type' => 'MEETING',
        'title' => 'অক্টোবর মাসের সার্বিক কাজের সমাপ্তি ও নভেম্বর কর্মপরিকল্পনা',
        'description' => 'পিএস ও একাডেমিক গবেষণা টিমের সাথে সারা মাসের কাজের অডিট ও মূল্যায়ন।',
        'date' => '2026-10-31',
        'start_time' => '11:00:00',
        'end_time' => '13:00:00',
        'location' => 'ব্যক্তিগত কার্যালয়, লালমাটিয়া',
        'topic' => 'নভেম্বরের সফর ও শীতকালীন মাহফিল সমন্বয়',
        'status' => 'CONFIRMED',
        'priority' => 'MEDIUM',
        'preparation_required' => 0,
        'travel_required' => 0,
    ],
    [
        'user_id' => 1,
        'type' => 'CLASS',
        'title' => 'তাফসিরুল কুরআন ধারাবাহিক দরস: সূরা আল-বাকারাহ #২২ (মাসিক সমাপ্তি সেশন)',
        'description' => 'সূরা আল-বাকারাহ শেষ তিন আয়াত ও ক্ষমা প্রার্থনার দোয়া।',
        'date' => '2026-10-31',
        'start_time' => '21:00:00',
        'end_time' => '22:30:00',
        'location' => 'অনলাইন স্টুডিও ও জুম লাইভ',
        'topic' => 'আমনার রাসুলু... দোয়া ও ক্ষমার চূড়ান্ত আরজি',
        'status' => 'CONFIRMED',
        'priority' => 'HIGH',
        'preparation_required' => 1,
        'travel_required' => 0,
    ]
];

$insertStmt = $db->prepare("
    INSERT INTO activities (
        user_id, type, title, description, date, start_time, end_time,
        timezone, location, topic, status, priority, preparation_required,
        travel_required, is_private, source, created_by
    ) VALUES (
        :user_id, :type, :title, :description, :date, :start_time, :end_time,
        'Asia/Dhaka', :location, :topic, :status, :priority, :prep,
        :travel, 0, 'OCTOBER_SEED', 1
    )
");

foreach ($octoberActivities as $act) {
    $insertStmt->execute([
        ':user_id' => $act['user_id'],
        ':type' => $act['type'],
        ':title' => $act['title'],
        ':description' => $act['description'],
        ':date' => $act['date'],
        ':start_time' => $act['start_time'],
        ':end_time' => $act['end_time'],
        ':location' => $act['location'],
        ':topic' => $act['topic'],
        ':status' => $act['status'],
        ':priority' => $act['priority'],
        ':prep' => $act['preparation_required'],
        ':travel' => $act['travel_required'],
    ]);
}
echo "Inserted " . count($octoberActivities) . " activities for October 2026!\n";

// 3. Update October 2026 Fridays in jumua_events
$octoberFridays = [
    [
        'date' => '2026-10-02',
        'friday_number' => 1,
        'mosque_id' => 2, // Sobhanbagh
        'contact_person' => 'হাজী রফিকুল ইসলাম',
        'phone' => '+8801819234567',
        'status' => 'COMPLETED',
        'khutbah_topic' => 'কুরআনের আলোকে সামাজিক সদাচার ও প্রতিবেশীর অধিকার',
        'notes' => 'সোবহানবাগ জামে মসজিদ কমিটি কর্তৃক আমন্ত্রিত। সফলভাবে খুতবাহ সম্পন্ন হয়েছে।',
        'preparation_status' => 'READY',
    ],
    [
        'date' => '2026-10-09',
        'friday_number' => 2,
        'mosque_id' => 5, // Baitul Aman
        'contact_person' => 'প্রকৌশলী মো. মহিউদ্দিন',
        'phone' => '+8801712987654',
        'status' => 'CONFIRMED',
        'khutbah_topic' => 'পারিবারিক শান্তি, দাম্পত্য বোঝাপড়া ও পিতা-মাতার হক',
        'notes' => 'বাইতুল আমান জামে মসজিদে নির্ধারিত। মাইক ও রেকর্ডিং টেস্ট নিশ্চিত করা হয়েছে।',
        'preparation_status' => 'READY',
    ],
    [
        'date' => '2026-10-16',
        'friday_number' => 3,
        'mosque_id' => 3, // Gulshan Society
        'contact_person' => 'ইঞ্জিনিয়ার মোশাররফ হোসেন',
        'phone' => '+8801799887766',
        'status' => 'CONFIRMED',
        'khutbah_topic' => 'ডিজিটাল যুগে সন্তানের লালন-পালন ও তরুণ সমাজের আত্মশুদ্ধি',
        'notes' => 'গুলশান সোসাইটি জামে মসজিদ কমিটি। যুবসমাজ ও তরুণদের উপস্থিতি বেশি থাকবে।',
        'preparation_status' => 'IN_PROGRESS',
    ],
    [
        'date' => '2026-10-23',
        'friday_number' => 4,
        'mosque_id' => 4, // Uttara Sector 7
        'contact_person' => 'ড. এনামুল করিম (মুতাওয়াল্লী)',
        'phone' => '+8801744112233',
        'status' => 'CONFIRMED',
        'khutbah_topic' => 'অর্থনৈতিক সুবিচার, ব্যবসায়িক সততা ও হালাল জীবিকার বরকত',
        'notes' => 'ব্যবসায়ী সমাজের নৈতিক মূল্যবোধ বিষয়ে আলোচনা। সময়মতো জুমার সালাতের ইমামতি।',
        'preparation_status' => 'NOT_STARTED',
    ],
    [
        'date' => '2026-10-30',
        'friday_number' => 5,
        'mosque_id' => 1, // Baitul Mukarram National Mosque
        'contact_person' => 'খতীব সমন্বয় কমিটি',
        'phone' => '+8801711111111',
        'status' => 'CONFIRMED',
        'khutbah_topic' => 'আখেরাতমুখী জীবনদর্শন, সত্যবাদিতা ও তাকওয়ার প্রভাব',
        'notes' => 'জাতীয় মসজিদে বিশেষ জুমার বয়ান ও নামাজ পরিচালনা। রাষ্ট্রীয় মিডিয়া কাভারেজ।',
        'preparation_status' => 'NOT_STARTED',
    ]
];

$jumuaStmt = $db->prepare("
    INSERT INTO jumua_events (
        date, friday_number, mosque_id, contact_person, phone,
        status, khutbah_topic, notes, preparation_status, created_by
    ) VALUES (
        :date, :friday_number, :mosque_id, :contact_person, :phone,
        :status, :khutbah_topic, :notes, :prep, 1
    )
    ON DUPLICATE KEY UPDATE
        mosque_id = VALUES(mosque_id),
        contact_person = VALUES(contact_person),
        phone = VALUES(phone),
        status = VALUES(status),
        khutbah_topic = VALUES(khutbah_topic),
        notes = VALUES(notes),
        preparation_status = VALUES(preparation_status)
");

foreach ($octoberFridays as $jf) {
    $jumuaStmt->execute([
        ':date' => $jf['date'],
        ':friday_number' => $jf['friday_number'],
        ':mosque_id' => $jf['mosque_id'],
        ':contact_person' => $jf['contact_person'],
        ':phone' => $jf['phone'],
        ':status' => $jf['status'],
        ':khutbah_topic' => $jf['khutbah_topic'],
        ':notes' => $jf['notes'],
        ':prep' => $jf['preparation_status']
    ]);
}
echo "Seeded all 5 Fridays for October 2026!\n";

echo "Done! October 2026 is fully populated with creative scholarly content.\n";
